/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>


int getTheAnswer() {
    return 42;
}

class Task {
public:
    void solve(std::istream &in, std::ostream &out) {
        int x;
        in >> x;
        out << x + getTheAnswer() << "\n";
    }
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    Task solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}