/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <bits/stdc++.h>

using namespace std;

class ATemporarilyUnavailable {
public:
    void solve(std::istream &in, std::ostream &out) {

        int a, b, c, r;
        in >> a >> b >> c >> r;

        if (a > b) swap(a, b);

        int x = max(a, c - r);
        int y = min(b, c + r);

        if (x > b || y < a) {
            out << b - a << '\n';
        } else if (y < x) {
            out << 0 << '\n';
        } else {
            out << (b - a) - (y - x) << '\n';
        }
    }
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    ATemporarilyUnavailable solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    int n;
    in >> n;
    for (int i = 0; i < n; ++i) {
        solver.solve(in, out);
    }

    return 0;
}